name: send_telegram_action

on: [push]

jobs:
  envio_mensaje:
    runs-on: ubuntu-latest
   - name: Enviar mensaje
       steps:
        - name: Obtener el código del repositorio
          uses: actions/checkout@v2
        - name: Ejecutar la action creada por nosotros mismos
          with:
            TOKEN: ${{ secrets.TOKEN }}
            CHAT_ID: ${{ secrets.CHAT_ID }}
            NOMBRE: ${{ secrets.NOMBRE }}
          run: npm i node-telegram-bot-api && node main.js 